[global]
   workgroup = NORTHWIND
   server string = Northwind Ops Files
   security = user
   map to guest = Never
   load printers = No

[OpsFiles]
   path = /shares/OpsFiles
   valid users = lisa
   read only = Yes
   browseable = Yes
