# CYCLE8: minimal IMAP for lisa / sunshine (L2)
protocols = imap
listen = *
mail_location = maildir:~/Maildir
disable_plaintext_auth = no
auth_mechanisms = plain login
ssl = no
userdb {
  driver = passwd
}
passdb {
  driver = shadow
}
service imap-login {
  inet_listener imap {
    port = 143
  }
}
