/**
 * v0.1.3 — Session Concept
 *
 * Shape of the decoded JWT payload after verification. This interface is
 * used by JwtAuthGuard (when it verifies incoming tokens) and by
 * CurrentUser decorator (when it reads request.user).
 *
 * VULN (v0.4.0): Role claim added to the payload (CWE-639). The role is
 *       stored in the JWT and NOT re-validated server-side during v0.4.0-v0.4.2.
 *       An attacker who knows the hardcoded JWT secret (v0.1.3, 'kc-secret')
 *       can sign a JWT with `role: 'admin'` and escalate privileges.
 *       Remediation (v2.4.0): Guards re-validate role from the database
 *       on every request, ignoring the JWT role claim.
 *
 * VULN: `sub` is a sequential string ID ("1", "2", "3"...) generated by
 *       UsersService.create(). An attacker who obtains any valid JWT can
 *       trivially guess other user IDs by incrementing/decrementing.
 *       CWE-330 (Use of Insufficiently Random Values) | A01:2025 Broken Access Control
 *       Remediation (v2.0.0): UUIDs (v4) for all identifiers.
 *
 * Fields:
 *   sub   — User ID. Maps to User.id in PostgreSQL. Required.
 *   role  — User role (added v0.4.0). Values: 'user' or 'admin' (extended in v0.4.3).
 *           TRUSTED WITHOUT RE-VALIDATION DURING V0.4.0-V0.4.2 (CWE-639).
 *   iat   — Issued-at timestamp (seconds since epoch). Auto-added by the
 *           jsonwebtoken library when JwtService.sign() is called. We never
 *           set this manually. Optional in the type because it only exists
 *           after signing, not when constructing the payload to sign.
 */
export interface JwtPayload {
  sub: string; // User ID — sequential, predictable (CWE-330)
  role?: 'user' | 'admin'; // User privilege level (v0.4.0+), trusted without re-validation (CWE-639)
  iat?: number; // Issued-at — auto-added by jsonwebtoken, not set manually
}
