/**
 * v0.1.3 — Session Concept
 *
 * Shape of the decoded JWT payload after verification. This interface is
 * used by JwtAuthGuard (when it verifies incoming tokens) and by
 * CurrentUser decorator (when it reads request.user).
 *
 * The payload is intentionally minimal — only `sub` (the user ID). There
 * is no role, email, or scope claim. This means:
 *   - The backend must look up the user from the store on every protected
 *     request if it needs anything beyond the user ID.
 *   - There is no way to revoke permissions via the token itself.
 *
 * VULN: `sub` is a sequential string ID ("1", "2", "3"...) generated by
 *       UsersService.create(). An attacker who obtains any valid JWT can
 *       trivially guess other user IDs by incrementing/decrementing.
 *       CWE-330 (Use of Insufficiently Random Values) | A01:2021 Broken Access Control
 *       Remediation (v2.0.0): UUIDs (v4) for all identifiers.
 *
 * Fields:
 *   sub  — User ID. Maps to User.id in the in-memory store. Required.
 *   iat  — Issued-at timestamp (seconds since epoch). Auto-added by the
 *          jsonwebtoken library when JwtService.sign() is called. We never
 *          set this manually. Optional in the type because it only exists
 *          after signing, not when constructing the payload to sign.
 */
export interface JwtPayload {
  sub: string; // User ID — sequential, predictable (CWE-330)
  iat?: number; // Issued-at — auto-added by jsonwebtoken, not set manually
}
